### ISSUE TITLE
RuntimeError: ones needs to be contiguous

### ISSUE THREAD

**Issue by Ystartff** [fxxJuses/MICFormer#4]
Traceback (most recent call last):
  File "MicFormer/train_mmwhs_noPad.py", line 414, in <module>
    main(arguments)
  File "MicFormer/train_mmwhs_noPad.py", line 200, in main
    loss_.backward()
  File "/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: ones needs to be contiguous

**Comment by Ystartff** [comment]
Can you give us the configuration of your virtual environment?

**Comment by yy3020195524** [comment]
11/10000
实时翻译
11/10000 real-time translation and translation. Excuse me, have you solved it yet

划译
Excuse me, have you solved it yet

**Comment by yy3020195524** [comment]
> Traceback (most recent call last): File "MicFormer/train_mmwhs_noPad.py", line 414, in main(arguments) File "MicFormer/train_mmwhs_noPad.py", line 200, in main loss_.backward() File "/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/autograd/**init**.py", line 156, in backward allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag RuntimeError: ones needs to be contiguous

Excuse me, have you solved it yet

**Comment by lirui54784** [comment]
> > Traceback (most recent call last): File "MicFormer/train_mmwhs_noPad.py", line 414, in main(arguments) File "MicFormer/train_mmwhs_noPad.py", line 200, in main loss_.backward() File "/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/autograd/**init**.py", line 156, in backward allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag RuntimeError: ones needs to be contiguous
> 
> Excuse me, have you solved it yet

Hello, I have encountered the same problem. Have you solved it yet

**Comment by yy3020195524** [comment]
> > > 回溯（最近调用最后一次）： 文件 “MicFormer/train_mmwhs_noPad.py”， 第 414 行， 在 main（arguments） 文件 “MicFormer/train_mmwhs_noPad.py”， 第 200 行， 在 main loss_.backward（） 文件 “/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/_tensor.py”， 第 307 行， 在后向 torch.autograd.backward（self， gradient， retain_graph， create_graph， inputs=inputs） 文件 “/home/linda/anaconda3/envs/yyf1/lib/python3.7/site-packages/torch/autograd/**init**.py“，第 156 行，向后 allow_unreachable=True， accumulate_grad=True） # allow_unreachable标志 RuntimeError：1 需要连续
> > 
> > 
> > 对不起，你解决了吗
> 
> 您好，我遇到了同样的问题。你解决了吗

我换了一个环境就解决了
